services:
  mysql:
   image: mysql:8.0
   container_name: lorian_bank_database_container
   restart: unless-stopped
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lorian_bank
   ports:
      - "3306:3306"
   volumes:
      - lorian_bank_data:/var/lib/mysql
   healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 2s
        retries: 10

  lorianbank:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lorian_bank?useTimezone=True&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      restart: on-failure

volumes:
   lorian_bank_data: